use crate::error::{AppError, Result};
use crate::state::AppState;
use crate::utils::{
    append_log, build_app_state, http_url_host, state_directory, validate_http_url,
    COOKIE_HEADER_EXPIRY,
};
use std::collections::BTreeSet;
use std::fs;
use tauri::{AppHandle, Emitter, Manager, WebviewWindowBuilder, WebviewUrl, WindowEvent};

const DEFAULT_LOGIN_URL: &str = "https://passport.bilibili.com/login";
const DEFAULT_COOKIE_LOOKUP_URL: &str = "https://www.bilibili.com";

/// Resolves which page to open for login and which URL to read cookies back from,
/// based on the site the user was trying to reach. Bilibili keeps its known-good
/// dedicated login page; every other site falls back to its own homepage.
fn resolve_login_target(target_url: Option<&str>) -> (String, String) {
    let host = target_url
        .filter(|url| validate_http_url(url).is_ok())
        .and_then(http_url_host);

    let Some(host) = host else {
        return (DEFAULT_LOGIN_URL.to_string(), DEFAULT_COOKIE_LOOKUP_URL.to_string());
    };

    if host.ends_with("bilibili.com") {
        return (DEFAULT_LOGIN_URL.to_string(), DEFAULT_COOKIE_LOOKUP_URL.to_string());
    }

    let site_url = format!("https://{host}/");
    (site_url.clone(), site_url)
}

async fn sync_webview_cookies_internal(app: &AppHandle, cookie_lookup_url: &str) -> Result<AppState> {
    let mut cookies = Vec::new();

    let lookup_url = tauri::Url::parse(cookie_lookup_url)?;
    let fallback_host = http_url_host(cookie_lookup_url).unwrap_or_default();

    let main_window = app
        .get_webview_window("main")
        .ok_or_else(|| AppError::Custom("Main window not found".to_string()))?;

    if let Ok(c) = main_window.cookies_for_url(lookup_url) {
        cookies.extend(c);
    }

    let mut lines = Vec::new();
    lines.push("# Netscape HTTP Cookie File".to_string());
    lines.push("# This file was generated by yt-dlp-tauri webview sync".to_string());
    lines.push(String::new());

    let mut seen = BTreeSet::new();

    let mut add_cookie = |cookie: &tauri::webview::Cookie<'static>| {
        let name = cookie.name();
        let domain = cookie
            .domain()
            .map(str::to_string)
            .unwrap_or_else(|| fallback_host.clone());
        if domain.is_empty() {
            return;
        }
        if seen.contains(&(domain.clone(), name.to_string())) {
            return;
        }
        seen.insert((domain.clone(), name.to_string()));

        let include_subdomains = if domain.starts_with('.') { "TRUE" } else { "FALSE" };
        let path = cookie.path().unwrap_or("/");
        let secure = if cookie.secure().unwrap_or(false) {
            "TRUE"
        } else {
            "FALSE"
        };
        let value = cookie.value();

        lines.push(format!(
            "{domain}\t{include_subdomains}\t{path}\t{secure}\t{COOKIE_HEADER_EXPIRY}\t{name}\t{value}"
        ));
    };

    for cookie in &cookies {
        add_cookie(cookie);
    }

    if seen.is_empty() {
        return Err(AppError::Custom(
            "No login cookies found. Please make sure you are logged in.".to_string(),
        ));
    }

    let state_dir = state_directory()?;
    fs::create_dir_all(&state_dir)?;

    let cookies_txt_path = state_dir.join("cookies.txt");
    fs::write(&cookies_txt_path, lines.join("\n"))?;

    fs::write(
        state_dir.join("cookies-file.txt"),
        cookies_txt_path.display().to_string(),
    )?;

    let _ = app.emit("cookies-synced", ());

    build_app_state(String::new())
}

#[tauri::command]
pub async fn open_login_window(app: AppHandle, target_url: Option<String>) -> Result<()> {
    let (login_url, cookie_lookup_url) = resolve_login_target(target_url.as_deref());

    tauri::async_runtime::spawn(async move {
        if let Some(window) = app.get_webview_window("login") {
            let _ = window.set_focus();
        } else {
            let url = match tauri::Url::parse(&login_url) {
                Ok(u) => u,
                Err(e) => {
                    append_log("login", &format!("Failed to parse login URL: {e}"));
                    return;
                }
            };

            let builder = WebviewWindowBuilder::new(&app, "login", WebviewUrl::External(url))
                .title("Web Login")
                .inner_size(800.0, 600.0);

            match builder.build() {
                Ok(window) => {
                    let app_handle = app.clone();
                    window.on_window_event(move |event| {
                        if let WindowEvent::Destroyed = event {
                            let app_clone = app_handle.clone();
                            let cookie_lookup_url = cookie_lookup_url.clone();
                            tauri::async_runtime::spawn(async move {
                                if let Err(e) =
                                    sync_webview_cookies_internal(&app_clone, &cookie_lookup_url).await
                                {
                                    append_log("login", &format!("Cookie auto-sync failed: {e}"));
                                } else {
                                    append_log("login", "Cookie auto-sync successful.");
                                }
                            });
                        }
                    });
                }
                Err(e) => {
                    append_log("login", &format!("Failed to build login window: {e}"));
                }
            }
        }
    });
    Ok(())
}

#[tauri::command]
pub async fn sync_webview_cookies(app: AppHandle) -> Result<AppState> {
    sync_webview_cookies_internal(&app, DEFAULT_COOKIE_LOOKUP_URL).await
}
