use crate::error::{AppError, Result};
use crate::state::AppState;
use crate::utils::{
    append_log, build_app_state, state_directory,
    COOKIE_HEADER_EXPIRY,
};
use std::collections::BTreeSet;
use std::fs;
use tauri::{AppHandle, Emitter, Manager, WebviewWindowBuilder, WebviewUrl, WindowEvent};

async fn sync_webview_cookies_internal(app: &AppHandle) -> Result<AppState> {
    let mut cookies = Vec::new();

    let bilibili_url = tauri::Url::parse("https://www.bilibili.com")?;

    let main_window = app
        .get_webview_window("main")
        .ok_or_else(|| AppError::Custom("Main window not found".to_string()))?;
    
    if let Ok(c) = main_window.cookies_for_url(bilibili_url) {
        cookies.extend(c);
    }

    let mut lines = Vec::new();
    lines.push("# Netscape HTTP Cookie File".to_string());
    lines.push("# This file was generated by yt-dlp-tauri webview sync".to_string());
    lines.push(String::new());

    let mut seen = BTreeSet::new();

    let mut add_cookie = |cookie: &tauri::webview::Cookie<'static>, domain: &str| {
        let name = cookie.name();
        if seen.contains(&(domain.to_string(), name.to_string())) {
            return;
        }
        seen.insert((domain.to_string(), name.to_string()));

        let include_subdomains = "TRUE";
        let path = cookie.path().unwrap_or("/");
        let secure = if cookie.secure().unwrap_or(false) {
            "TRUE"
        } else {
            "FALSE"
        };
        let value = cookie.value();

        lines.push(format!(
            "{domain}\t{include_subdomains}\t{path}\t{secure}\t{COOKIE_HEADER_EXPIRY}\t{name}\t{value}"
        ));
    };

    for cookie in &cookies {
        add_cookie(cookie, ".bilibili.com");
    }

    if seen.is_empty() {
        return Err(AppError::Custom(
            "No login cookies found. Please make sure you are logged in.".to_string(),
        ));
    }

    let state_dir = state_directory()?;
    fs::create_dir_all(&state_dir)?;

    let cookies_txt_path = state_dir.join("cookies.txt");
    fs::write(&cookies_txt_path, lines.join("\n"))?;

    fs::write(
        state_dir.join("cookies-file.txt"),
        cookies_txt_path.display().to_string(),
    )?;

    let _ = app.emit("cookies-synced", ());

    build_app_state(String::new())
}

#[tauri::command]
pub async fn open_login_window(app: AppHandle) -> Result<()> {
    tauri::async_runtime::spawn(async move {
        if let Some(window) = app.get_webview_window("login") {
            let _ = window.set_focus();
        } else {
            let url = match tauri::Url::parse("https://passport.bilibili.com/login") {
                Ok(u) => u,
                Err(e) => {
                    append_log("login", &format!("Failed to parse login URL: {e}"));
                    return;
                }
            };

            let builder = WebviewWindowBuilder::new(&app, "login", WebviewUrl::External(url))
                .title("Bilibili Login")
                .inner_size(800.0, 600.0);

            match builder.build() {
                Ok(window) => {
                    let app_handle = app.clone();
                    window.on_window_event(move |event| {
                        if let WindowEvent::Destroyed = event {
                            let app_clone = app_handle.clone();
                            tauri::async_runtime::spawn(async move {
                                if let Err(e) = sync_webview_cookies_internal(&app_clone).await {
                                    append_log("login", &format!("Cookie auto-sync failed: {e}"));
                                } else {
                                    append_log("login", "Cookie auto-sync successful.");
                                }
                            });
                        }
                    });
                }
                Err(e) => {
                    append_log("login", &format!("Failed to build login window: {e}"));
                }
            }
        }
    });
    Ok(())
}

#[tauri::command]
pub async fn sync_webview_cookies(app: AppHandle) -> Result<AppState> {
    sync_webview_cookies_internal(&app).await
}
