use super::net::http_url_host;
use super::paths::state_directory;
use crate::error::{AppError, Result};
use crate::state::PreparedCookiesFile;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

pub const COOKIE_HEADER_EXPIRY: &str = "2147483647";

pub fn cookies_file_state_path() -> Result<PathBuf> {
    Ok(state_directory()?.join("cookies-file.txt"))
}

pub fn cookies_file() -> Result<Option<PathBuf>> {
    let configured = cookies_file_state_path()?;
    if configured.exists() {
        let value = fs::read_to_string(configured)?;
        let value = value.trim();
        if !value.is_empty() {
            return Ok(Some(PathBuf::from(value)));
        }
    }

    Ok(None)
}

pub fn prepared_cookies_file_for_url(url: &str) -> Result<Option<PreparedCookiesFile>> {
    let Some(path) = cookies_file()? else {
        return Ok(None);
    };

    prepare_cookies_file_path_for_url(&path, url).map(Some)
}

pub fn validate_cookies_file_path(path: &Path) -> Result<()> {
    if !path.is_file() {
        return Err(AppError::Custom(format!("Cookie file does not exist: {}", path.display())));
    }

    fs::File::open(path)
        .map(|_| ())
        .map_err(|error| AppError::Custom(format!("Cookie file cannot be opened: {}: {error}", path.display())))
}

pub fn prepare_cookies_file_path_for_url(
    path: &Path,
    url: &str,
) -> Result<PreparedCookiesFile> {
    validate_cookies_file_path(path)?;
    let content = fs::read_to_string(path).map_err(|error| {
        AppError::Custom(format!(
            "Cookie file cannot be read as text: {}: {error}",
            path.display()
        ))
    })?;

    if is_netscape_cookie_content(&content) {
        return Ok(PreparedCookiesFile::new(path.to_path_buf(), false));
    }

    if !looks_like_cookie_header_content(&content) {
        return Err(AppError::Custom(
            "Cookie file must be Netscape cookies.txt or a one-line Cookie header such as `a=b; c=d`."
                .to_string(),
        ));
    }

    let converted = cookie_header_to_netscape_content(url, &content)?;
    let converted_path = temp_cookies_file_path();
    fs::write(&converted_path, converted).map_err(|error| {
        AppError::Custom(format!(
            "Failed to prepare temporary Cookie header file at {}: {error}",
            converted_path.display()
        ))
    })?;

    Ok(PreparedCookiesFile::new(converted_path, true))
}

pub fn yt_dlp_cookie_args(cookies_file: Option<&Path>) -> Vec<String> {
    cookies_file
        .map(|path| vec!["--cookies".to_string(), path.display().to_string()])
        .unwrap_or_default()
}

pub fn is_netscape_cookie_content(content: &str) -> bool {
    content.lines().any(|line| {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            return false;
        }

        line.split('\t').count() == 7
    })
}

pub fn looks_like_cookie_header_content(content: &str) -> bool {
    parse_cookie_header_pairs(content)
        .map(|pairs| !pairs.is_empty())
        .unwrap_or(false)
}

pub fn cookie_header_to_netscape_content(url: &str, content: &str) -> Result<String> {
    let (domain, include_subdomains) = cookie_domain_for_url(url)?;
    let include_subdomains = if include_subdomains { "TRUE" } else { "FALSE" };
    let secure = if url.starts_with("https://") {
        "TRUE"
    } else {
        "FALSE"
    };
    let pairs = parse_cookie_header_pairs(content)?;
    if pairs.is_empty() {
        return Err(AppError::Custom("Cookie header file does not contain any cookie pairs.".to_string()));
    }

    let mut lines = vec![
        "# Netscape HTTP Cookie File".to_string(),
        "# Generated by yt-dlp-tauri from a Cookie header file.".to_string(),
    ];

    for (name, value) in pairs {
        lines.push(format!(
            "{domain}\t{include_subdomains}\t/\t{secure}\t{COOKIE_HEADER_EXPIRY}\t{name}\t{value}"
        ));
    }
    lines.push(String::new());
    Ok(lines.join("\n"))
}

pub fn parse_cookie_header_pairs(content: &str) -> Result<Vec<(String, String)>> {
    let joined = content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    let header = strip_cookie_header_prefix(&joined).trim();
    if !header.contains('=') {
        return Err(AppError::Custom("Cookie header file does not contain `name=value` pairs.".to_string()));
    }

    let mut pairs = Vec::new();
    for part in header.split(';') {
        let part = part.trim();
        if part.is_empty() {
            continue;
        }

        let Some((name, value)) = part.split_once('=') else {
            return Err(AppError::Custom(format!("Cookie header entry is missing `=`: {part}")));
        };
        let name = name.trim();
        if name.is_empty() || !is_safe_cookie_field(name) {
            return Err(AppError::Custom(format!(
                "Cookie header contains an invalid cookie name: {name}"
            )));
        }
        if !is_safe_cookie_field(value) {
            return Err(AppError::Custom(format!(
                "Cookie header contains an invalid value for {name}."
            )));
        }

        pairs.push((name.to_string(), value.trim().to_string()));
    }

    Ok(pairs)
}

fn strip_cookie_header_prefix(content: &str) -> &str {
    let trimmed = content.trim_start();
    if trimmed
        .get(..7)
        .map(|prefix| prefix.eq_ignore_ascii_case("cookie:"))
        .unwrap_or(false)
    {
        &trimmed[7..]
    } else {
        trimmed
    }
}

fn is_safe_cookie_field(value: &str) -> bool {
    !value
        .chars()
        .any(|character| character == '\t' || character == '\r' || character == '\n')
}

pub fn cookie_domain_for_url(url: &str) -> Result<(String, bool)> {
    let host = http_url_host(url)
        .ok_or_else(|| AppError::Custom("Unable to determine host for Cookie header conversion.".to_string()))?;
    if host == "localhost" || host.parse::<std::net::IpAddr>().is_ok() {
        return Ok((host, false));
    }

    let labels = host
        .split('.')
        .filter(|part| !part.is_empty())
        .collect::<Vec<_>>();
    if labels.len() < 2 {
        return Ok((host, false));
    }

    let base = if labels.len() > 2 && labels.first().is_some_and(|label| *label == "www") {
        labels[1..].join(".")
    } else if labels.len() > 2 {
        labels[labels.len() - 2..].join(".")
    } else {
        host
    };

    Ok((format!(".{base}"), true))
}

fn temp_cookies_file_path() -> PathBuf {
    let stamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_nanos())
        .unwrap_or_default();
    env::temp_dir().join(format!(
        "yt-dlp-tauri-cookies-{}-{stamp}.txt",
        std::process::id()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn omits_cookie_args_without_configured_file() {
        assert!(yt_dlp_cookie_args(None).is_empty());
    }

    #[test]
    fn passes_configured_cookie_file_to_yt_dlp() {
        let args = yt_dlp_cookie_args(Some(Path::new("account-cookies.txt")));

        assert_eq!(
            args,
            vec!["--cookies".to_string(), "account-cookies.txt".to_string()]
        );
    }

    #[test]
    fn converts_cookie_header_file_content_to_netscape_cookie_content() {
        let content = cookie_header_to_netscape_content(
            "https://www.bilibili.com/video/BV1test",
            "Cookie: buvid3=abc; bili_jct=token_value; CURRENT_FNVAL=2000",
        )
        .expect("cookie header should convert");

        assert_eq!(
            content,
            [
                "# Netscape HTTP Cookie File",
                "# Generated by yt-dlp-tauri from a Cookie header file.",
                ".bilibili.com\tTRUE\t/\tTRUE\t2147483647\tbuvid3\tabc",
                ".bilibili.com\tTRUE\t/\tTRUE\t2147483647\tbili_jct\ttoken_value",
                ".bilibili.com\tTRUE\t/\tTRUE\t2147483647\tCURRENT_FNVAL\t2000",
                "",
            ]
            .join("\n")
        );
    }

    #[test]
    fn converts_bare_cookie_header_file_content_to_netscape_cookie_content() {
        let content = cookie_header_to_netscape_content(
            "https://www.bilibili.com/video/BV1test",
            "buvid3=abc; bili_jct=token_value",
        )
        .expect("bare cookie header should convert");

        assert!(content.contains(".bilibili.com\tTRUE\t/\tTRUE\t2147483647\tbuvid3\tabc"));
        assert!(content.contains(".bilibili.com\tTRUE\t/\tTRUE\t2147483647\tbili_jct\ttoken_value"));
    }

    #[test]
    fn detects_netscape_cookie_content() {
        assert!(is_netscape_cookie_content(
            "# Netscape HTTP Cookie File\n.bilibili.com\tTRUE\t/\tFALSE\t0\tbuvid3\tabc\n"
        ));
        assert!(!is_netscape_cookie_content(
            "buvid3=abc; bili_jct=token_value"
        ));
    }
}
